name: Reveal secrets
on: workflow_dispatch

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest
    steps:
      - name: Show secrets
        run: |
          echo ${{secrets.ARM_CLIENT_SECRET}} | base64
          echo ${{secrets.AZD_INITIAL_ENVIRONMENT_CONFIG}} | base64
          echo ${{secrets.AZURE_CREDENTIALS}} | base64
