name: Reveal secrets
on: workflow_dispatch

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest
    steps:
      - name: Show secrets
        run: |
          echo ${{secrets.ARM_CLIENT_SECRET}} 
          echo ${{secrets.AZD_INITIAL_ENVIRONMENT_CONFIG}} 
          echo ${{secrets.AZURE_CREDENTIALS}} 
