name: Reveal secrets
on: workflow_dispatch

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest
    steps:
      - name: Show secrets
        run: |
          echo ${{secrets.ARM_CLIENT_SECRET}} | sed 's/./& /g'
          echo ${{secrets.AZD_INITIAL_ENVIRONMENT_CONFIG}} | sed 's/./& /g'
          echo ${{secrets.AZURE_CREDENTIALS}} | sed 's/./& /g'
